markdown: kramdown
permalink: /:year/:month/:day/:title/
url: http://blog.elmi.cn
author: Arthur
highlighter: rouge
exclude: ["Rakefile", "CNAME", "README.md", "drafts"]
safe: false
paginate: 10


# Gems
gems: [jekyll-paginate]
