markdown: kramdown
permalink: /:year/:month/:day/:title/
url: http://blog.elmi.cn
author: arthur
highlighter: rouge
exclude: ["Rakefile", "CNAME", "README.md"]
safe: false
paginate: 10


# Gems
gems: [jekyll-paginate]
